spring:
  config:
    import: optional:file:./config/secrets-test.yaml
  datasource:
    url: ${app.db.url}
    driver-class-name: org.h2.Driver
    username: ${app.db.username}
    password: ${app.db.password:}
