-- Initial admin credentials (plaintext for local dev reference):
--   username: admin
--   password: admin123
-- BCrypt hash regenerated by src/test/java/.../tools/BcryptHashGenerator.
INSERT INTO users (username, password_hash, email, role, created_at, updated_at)
VALUES ('admin',
        '$2a$10$dQGxTbwGHvetyc08FkVHyugcgGRvwpXpf1MvLFs5npeDEVe2RfSOK',
        'admin@awgdas.local',
        'ADMIN',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);
